import time
import RPi.GPIO as GPIO
GPIO.setmode(GPIO.BCM)
INPUTPIN = 4
BUZZER = 17
SERVO = 14
RS=27
EN=22
A=10
B=9
C=11
D=5
E=6
F=13
G=19
H=26
TT=0.007
AA = 25
BB = 8
CC = 7
DD = 12
ee=15
ff=18
gg=23
hh=24
GPIO.setup(AA, GPIO.OUT)
GPIO.setup(BB, GPIO.OUT)
GPIO.setup(CC, GPIO.OUT)
GPIO.setup(DD, GPIO.OUT)
GPIO.setup(ee, GPIO.OUT)
GPIO.setup(ff, GPIO.OUT)
GPIO.setup(gg, GPIO.OUT)
GPIO.setup(hh, GPIO.OUT)		
GPIO.setup(A, GPIO.OUT)
GPIO.setup(B, GPIO.OUT)
GPIO.setup(C, GPIO.OUT)
GPIO.setup(D, GPIO.OUT)
GPIO.setup(E, GPIO.OUT)
GPIO.setup(F, GPIO.OUT)
GPIO.setup(G, GPIO.OUT)
GPIO.setup(H, GPIO.OUT)
GPIO.setup(RS, GPIO.OUT)
GPIO.setup(EN, GPIO.OUT)
GPIO.setup(SERVO,GPIO.OUT)
GPIO.setup(INPUTPIN, GPIO.IN)
GPIO.setup(BUZZER, GPIO.OUT)
def lcdkc():
	                        #CMD38   
		                GPIO.output(RS,GPIO.LOW)
		                GPIO.output(A,GPIO.LOW)          
			        GPIO.output(B,GPIO.LOW)     
			        GPIO.output(C,GPIO.LOW)     
				GPIO.output(D,GPIO.HIGH)     
				GPIO.output(E,GPIO.HIGH)     
				GPIO.output(F,GPIO.HIGH)     
				GPIO.output(G,GPIO.LOW)     
				GPIO.output(H,GPIO.LOW)     
				GPIO.output(EN,GPIO.HIGH)         
				time.sleep(0.1)
				GPIO.output(EN,GPIO.LOW)
				#CMD01
				GPIO.output(RS,GPIO.LOW)
				GPIO.output(A,GPIO.HIGH)          
				GPIO.output(B,GPIO.LOW)     
				GPIO.output(C,GPIO.LOW)     
				GPIO.output(D,GPIO.LOW)     
				GPIO.output(E,GPIO.LOW)     
				GPIO.output(F,GPIO.LOW)     
				GPIO.output(G,GPIO.LOW)     
				GPIO.output(H,GPIO.LOW)     
				GPIO.output(EN,GPIO.HIGH)         
				time.sleep(0.1)
				GPIO.output(EN,GPIO.LOW)  
				#CMD0E   
				GPIO.output(RS,GPIO.LOW)
				GPIO.output(A,GPIO.LOW)          
				GPIO.output(B,GPIO.HIGH)     
				GPIO.output(C,GPIO.HIGH)     
				GPIO.output(D,GPIO.HIGH)     
				GPIO.output(E,GPIO.LOW)     
				GPIO.output(F,GPIO.LOW)     
				GPIO.output(G,GPIO.LOW)     
				GPIO.output(H,GPIO.LOW)     
				GPIO.output(EN,GPIO.HIGH)         
				time.sleep(0.1)
				GPIO.output(EN,GPIO.LOW)
				#K
				GPIO.output(RS,GPIO.HIGH)
				GPIO.output(A,GPIO.HIGH)          
				GPIO.output(B,GPIO.HIGH)     
				GPIO.output(C,GPIO.LOW)     
				GPIO.output(D,GPIO.HIGH)     
				GPIO.output(E,GPIO.LOW)     
				GPIO.output(F,GPIO.LOW)     
				GPIO.output(G,GPIO.HIGH)     
				GPIO.output(H,GPIO.LOW)     
				GPIO.output(EN,GPIO.HIGH)         
				time.sleep(0.1)
				GPIO.output(EN,GPIO.LOW)
				#N
				GPIO.output(RS,GPIO.HIGH)
				GPIO.output(A,GPIO.LOW)          
				GPIO.output(B,GPIO.HIGH)     	
				GPIO.output(C,GPIO.HIGH)     
				GPIO.output(D,GPIO.HIGH)     
				GPIO.output(E,GPIO.LOW)     
				GPIO.output(F,GPIO.LOW)     
				GPIO.output(G,GPIO.HIGH)     
				GPIO.output(H,GPIO.LOW)     
				GPIO.output(EN,GPIO.HIGH)         
				time.sleep(0.1)
				GPIO.output(EN,GPIO.LOW)
				#O
				GPIO.output(RS,GPIO.HIGH)
				GPIO.output(A,GPIO.HIGH)          
				GPIO.output(B,GPIO.HIGH)     
				GPIO.output(C,GPIO.HIGH)     
				GPIO.output(D,GPIO.HIGH)     
				GPIO.output(E,GPIO.LOW)     
				GPIO.output(F,GPIO.LOW)     
				GPIO.output(G,GPIO.HIGH)     
				GPIO.output(H,GPIO.LOW)     
				GPIO.output(EN,GPIO.HIGH)         
				time.sleep(0.1)
				GPIO.output(EN,GPIO.LOW)
				#B
				GPIO.output(RS,GPIO.HIGH)
				GPIO.output(A,GPIO.LOW)          
				GPIO.output(B,GPIO.HIGH)     
				GPIO.output(C,GPIO.LOW)     
				GPIO.output(D,GPIO.LOW)     
				GPIO.output(E,GPIO.LOW)     
				GPIO.output(F,GPIO.LOW)     
				GPIO.output(G,GPIO.HIGH)     
				GPIO.output(H,GPIO.LOW)     
				GPIO.output(EN,GPIO.HIGH)         
				time.sleep(0.1)
				GPIO.output(EN,GPIO.LOW)
				#SPACE
				GPIO.output(RS,GPIO.LOW)
				GPIO.output(A,GPIO.LOW)          
				GPIO.output(B,GPIO.LOW)     
				GPIO.output(C,GPIO.HIGH)     
				GPIO.output(D,GPIO.LOW)     
				GPIO.output(E,GPIO.HIGH)     
				GPIO.output(F,GPIO.LOW)     
				GPIO.output(G,GPIO.LOW)     
				GPIO.output(H,GPIO.LOW)     
				GPIO.output(EN,GPIO.HIGH)         
				time.sleep(0.1)
				GPIO.output(EN,GPIO.LOW)
				#C
				GPIO.output(RS,GPIO.HIGH)
				GPIO.output(A,GPIO.HIGH)          
				GPIO.output(B,GPIO.HIGH)     
				GPIO.output(C,GPIO.LOW)     
				GPIO.output(D,GPIO.LOW)     
				GPIO.output(E,GPIO.LOW)     
				GPIO.output(F,GPIO.LOW)     
				GPIO.output(G,GPIO.HIGH)     
				GPIO.output(H,GPIO.LOW)     
				GPIO.output(EN,GPIO.HIGH)         
				time.sleep(0.1)
				GPIO.output(EN,GPIO.LOW)
				#L
				GPIO.output(RS,GPIO.HIGH)
				GPIO.output(A,GPIO.LOW)          
				GPIO.output(B,GPIO.LOW)     
				GPIO.output(C,GPIO.HIGH)     
				GPIO.output(D,GPIO.HIGH)     
				GPIO.output(E,GPIO.LOW)     
				GPIO.output(F,GPIO.LOW)     
				GPIO.output(G,GPIO.HIGH)     
				GPIO.output(H,GPIO.LOW)     
				GPIO.output(EN,GPIO.HIGH)         
				time.sleep(0.1)
				GPIO.output(EN,GPIO.LOW)
				#O
				GPIO.output(RS,GPIO.HIGH)
				GPIO.output(A,GPIO.HIGH)          
				GPIO.output(B,GPIO.HIGH)     
				GPIO.output(C,GPIO.HIGH)     
				GPIO.output(D,GPIO.HIGH)     
				GPIO.output(E,GPIO.LOW)     
				GPIO.output(F,GPIO.LOW)     
				GPIO.output(G,GPIO.HIGH)     
				GPIO.output(H,GPIO.LOW)     
				GPIO.output(EN,GPIO.HIGH)         
				time.sleep(0.1)
				GPIO.output(EN,GPIO.LOW)
				#S
				GPIO.output(RS,GPIO.HIGH)
				GPIO.output(A,GPIO.HIGH)          
				GPIO.output(B,GPIO.HIGH)     
				GPIO.output(C,GPIO.LOW)     
				GPIO.output(D,GPIO.LOW)     
				GPIO.output(E,GPIO.HIGH)     
				GPIO.output(F,GPIO.LOW)     
				GPIO.output(G,GPIO.HIGH)     
				GPIO.output(H,GPIO.LOW)     
				GPIO.output(EN,GPIO.HIGH)         
				time.sleep(0.1)
				GPIO.output(EN,GPIO.LOW)
				#I
				GPIO.output(RS,GPIO.HIGH)
				GPIO.output(A,GPIO.HIGH)          
				GPIO.output(B,GPIO.LOW)     
				GPIO.output(C,GPIO.LOW)     
				GPIO.output(D,GPIO.HIGH)     
				GPIO.output(E,GPIO.LOW)     
				GPIO.output(F,GPIO.LOW)     
				GPIO.output(G,GPIO.HIGH)     
				GPIO.output(H,GPIO.LOW)     
				GPIO.output(EN,GPIO.HIGH)         
				time.sleep(0.1)
				GPIO.output(EN,GPIO.LOW)
				#N
				GPIO.output(RS,GPIO.HIGH)
				GPIO.output(A,GPIO.LOW)          
				GPIO.output(B,GPIO.HIGH)     
				GPIO.output(C,GPIO.HIGH)     
				GPIO.output(D,GPIO.HIGH)     
				GPIO.output(E,GPIO.LOW)     
				GPIO.output(F,GPIO.LOW)     
				GPIO.output(G,GPIO.HIGH)     
				GPIO.output(H,GPIO.LOW)     
				GPIO.output(EN,GPIO.HIGH)         
				time.sleep(0.1)
				GPIO.output(EN,GPIO.LOW)
				#G    
				GPIO.output(RS,GPIO.HIGH)
				GPIO.output(A,GPIO.HIGH)          
				GPIO.output(B,GPIO.HIGH)     
				GPIO.output(C,GPIO.HIGH)     
				GPIO.output(D,GPIO.LOW)     
				GPIO.output(E,GPIO.LOW)     
				GPIO.output(F,GPIO.LOW)     
				GPIO.output(G,GPIO.HIGH)     
				GPIO.output(H,GPIO.LOW)     
				GPIO.output(EN,GPIO.HIGH)         
				time.sleep(0.1)
				GPIO.output(EN,GPIO.LOW)
				time.sleep(1.5)
#CMD01
GPIO.output(RS,GPIO.LOW)
GPIO.output(A,GPIO.HIGH)          
GPIO.output(B,GPIO.LOW)     
GPIO.output(C,GPIO.LOW)     
GPIO.output(D,GPIO.LOW)     
GPIO.output(E,GPIO.LOW)     
GPIO.output(F,GPIO.LOW)     
GPIO.output(G,GPIO.LOW)     
GPIO.output(H,GPIO.LOW)     
GPIO.output(EN,GPIO.HIGH)         
time.sleep(0.1)
GPIO.output(EN,GPIO.LOW)
                 
	
while True:
    if (GPIO.input(INPUTPIN) == 0):
		        GPIO.output(BUZZER,GPIO.HIGH)
		        lcdkc()
                        for i in range(192):
					GPIO.output(DD,GPIO.HIGH)        
					time.sleep(TT)
					GPIO.output(DD,GPIO.LOW)
					time.sleep(TT)
					GPIO.output(CC,GPIO.HIGH)
					GPIO.output(DD,GPIO.HIGH)
					time.sleep(TT)
					GPIO.output(CC,GPIO.LOW)
					GPIO.output(DD,GPIO.LOW)
					time.sleep(TT)
					GPIO.output(CC,GPIO.HIGH)
					time.sleep(TT)
					GPIO.output(CC,GPIO.LOW)
					time.sleep(TT)
					GPIO.output(BB,GPIO.HIGH)
					GPIO.output(CC,GPIO.HIGH)
					time.sleep(TT)
					GPIO.output(BB,GPIO.LOW)
					GPIO.output(CC,GPIO.LOW)
					time.sleep(TT)
					GPIO.output(BB,GPIO.HIGH)
					time.sleep(TT)
					GPIO.output(BB,GPIO.LOW)
					time.sleep(TT)
					GPIO.output(AA,GPIO.HIGH)
					GPIO.output(BB,GPIO.HIGH)
					time.sleep(TT)
					GPIO.output(AA,GPIO.LOW)
					GPIO.output(BB,GPIO.LOW)
					time.sleep(TT)
					GPIO.output(AA,GPIO.HIGH)
					time.sleep(TT)
					GPIO.output(AA,GPIO.LOW)
					time.sleep(TT)
					GPIO.output(AA,GPIO.HIGH)
					GPIO.output(DD,GPIO.HIGH)
					time.sleep(TT)
					GPIO.output(AA,GPIO.LOW)
					GPIO.output(DD,GPIO.LOW)
					time.sleep(TT)
			pwm=GPIO.PWM(SERVO,100)
			pwm.start(5)
			angle1=10
			duty1=float(angle1)/10 + 2.5
			angle2=90
			duty2=float(angle2)/10 + 2.5
			pwm.ChangeDutyCycle(duty2)
			time.sleep(0.8)
                        for i in range(128):
				GPIO.output(ee,GPIO.HIGH)
				GPIO.output(hh,GPIO.HIGH)
				time.sleep(TT)
				GPIO.output(ee,GPIO.LOW)
				GPIO.output(hh,GPIO.LOW)
				time.sleep(TT)
				GPIO.output(ee,GPIO.HIGH)
				time.sleep(TT)
				GPIO.output(ee,GPIO.LOW)
				time.sleep(TT)
				GPIO.output(ff,GPIO.HIGH)
				GPIO.output(ee,GPIO.HIGH)
				time.sleep(TT)
				GPIO.output(ff,GPIO.LOW)
				GPIO.output(ee,GPIO.LOW)
				time.sleep(TT)
				GPIO.output(ff,GPIO.HIGH)
				time.sleep(TT)
				GPIO.output(ff,GPIO.LOW)
				time.sleep(TT)
				GPIO.output(ff,GPIO.HIGH)
				GPIO.output(gg,GPIO.HIGH)
				time.sleep(TT)
				GPIO.output(ff,GPIO.LOW)
				GPIO.output(gg,GPIO.LOW)
				time.sleep(TT)
				GPIO.output(gg,GPIO.HIGH)
				time.sleep(TT)
				GPIO.output(gg,GPIO.LOW)
				time.sleep(TT)
				GPIO.output(gg,GPIO.HIGH)
				GPIO.output(hh,GPIO.HIGH)
				time.sleep(TT)
				GPIO.output(gg,GPIO.LOW)
				GPIO.output(hh,GPIO.LOW)
				time.sleep(TT)
				GPIO.output(hh,GPIO.HIGH)        
				time.sleep(TT)
				GPIO.output(hh,GPIO.LOW)
				time.sleep(TT)
			while True:
			    if (GPIO.input(INPUTPIN) == True):
				break
			    else:
				sleep.time(10)
			for i in range(128):
					GPIO.output(hh,GPIO.HIGH)        
					time.sleep(TT)
					GPIO.output(hh,GPIO.LOW)
					time.sleep(TT)
					GPIO.output(hh,GPIO.HIGH)
					GPIO.output(gg,GPIO.HIGH)
					time.sleep(TT)
					GPIO.output(hh,GPIO.LOW)
					GPIO.output(gg,GPIO.LOW)
					time.sleep(TT)
					GPIO.output(gg,GPIO.HIGH)
					time.sleep(TT)
					GPIO.output(gg,GPIO.LOW)
					time.sleep(TT)
					GPIO.output(ff,GPIO.HIGH)
					GPIO.output(gg,GPIO.HIGH)
					time.sleep(TT)
					GPIO.output(ff,GPIO.LOW)
					GPIO.output(gg,GPIO.LOW)
					time.sleep(TT)
					GPIO.output(ff,GPIO.HIGH)
					time.sleep(TT)
					GPIO.output(ff,GPIO.LOW)
					time.sleep(TT)
					GPIO.output(ee,GPIO.HIGH)
					GPIO.output(ff,GPIO.HIGH)
					time.sleep(TT)
					GPIO.output(ee,GPIO.LOW)
					GPIO.output(ff,GPIO.LOW)
					time.sleep(TT)
					GPIO.output(ee,GPIO.HIGH)
					time.sleep(TT)
					GPIO.output(ee,GPIO.LOW)
					time.sleep(TT)
					GPIO.output(ee,GPIO.HIGH)
					GPIO.output(hh,GPIO.HIGH)
					time.sleep(TT)
					GPIO.output(ee,GPIO.LOW)
					GPIO.output(hh,GPIO.LOW)
					time.sleep(TT)

			
			pwm.ChangeDutyCycle(duty1)
			time.sleep(0.8)
			time.sleep(1)
			GPIO.cleanup()

			GPIO.output(BUZZER,GPIO.LOW) 
                     
    else:
				GPIO.output(BUZZER,GPIO.LOW)    
sleep(1);
